apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.8.11
    chart: loki-simple-scalable
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: local
            local:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
        persistence:
          enabled: true
          storageClassName: longhorn
          size: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
