apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-promtail-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.0
    chart: promtail
    helm:
      values: |
        daemonset:
          tolerations:
            - operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
