apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.8.11
    chart: loki-simple-scalable
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: local
            local:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          schema_config:
            configs:
              - from: "2020-10-24"
                index:
                  period: 24h
                  prefix: index_
                object_store: filesystem
                schema: v13
                store: tsdb
          limits_config:
            retention_period: 30d
            enforce_metric_name: false
            reject_old_samples: false
            max_streams_per_user: 10000
            max_line_size: 256000
          compactor:
            working_directory: /var/loki/compactor
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          table_manager:
            retention_deletes_enabled: false
            retention_period: 30d
        persistence:
          enabled: true
          storageClassName: longhorn
          size: 200Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
