apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.8.11
    chart: loki-simple-scalable
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            type: local
            local:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          limits_config:
            ingestion_rate_mb: 10
            ingestion_burst_size_mb: 20
          chunk_store_config:
            max_chunk_age: 2h
          ingester:
            chunk_idle_period: 30m
            chunk_block_size: 262144
            chunk_target_size: 1572864
            max_chunk_age: 2h
            flush_check_period: 30s
        persistence:
          enabled: true
          storageClassName: longhorn
          size: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true