apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.37.0
    chart: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
