apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-promtail-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.0
    chart: promtail
    helm:
      values: |
        daemonset:
          tolerations:
            - operator: Exists
        config:
          clients:
            - url: http://loki-gateway/loki/api/v1/push
              timeout: 30s
              backoff_config:
                min_period: 500ms
                max_period: 5m
                max_retries: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
