# Default values for prometheus
replicas: 1
retention: "7d"
retentionSize: "60GB"

resources:
  requests:
    memory: "400Mi"
    cpu: "100m"
  limits:
    memory: "800Mi"
    cpu: "200m"

nodeSelector:
  node-type: worker

securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

serviceMonitorSelector:
  matchExpressions:
  - key: name
    operator: In
    values:
    - longhorn-prometheus-servicemonitor
    - kube-state-metrics
    - node-exporter
    - kubelet
    - traefik

storage:
  storageClassName: "longhorn"
  size: "100Gi"
