# Default values for prometheus
replicaCount: 1

retention: 7d

resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 200m
    memory: 400Mi

nodeSelector:
  node-type: worker

tolerations: []

affinity: {}

securityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

storage:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  size: 20Gi

serviceMonitorSelector:
  matchExpressions:
    - key: name
      operator: In
      values:
        - longhorn-prometheus-servicemonitor
        - kube-state-metrics
        - node-exporter
        - kubelet
        - traefik

# External service configuration
externalService:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: 192.168.0.205
  port: 9090

# Internal service configuration
internalService:
  enabled: true
  type: ClusterIP
  port: 9090
  sessionAffinity: ClientIP
