apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: helm/open-webui
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: open-webui
    managedFieldsManagers:
    - kubectl-set
