apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: helm/ollama
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
