apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: argocd/apps/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    syncOptions:
      - CreateNamespace=true