apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system-namespace-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: argocd/apps/longhorn-system
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
