apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.service.port }}
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
