apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
    name: {{ include "kube-state-metrics.fullname" . }}
    prometheus-enabled: "true"
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http-metrics
      interval: 30s
      honorLabels: true
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "kube-state-metrics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: exporter
      app.kubernetes.io/part-of: kube-prometheus
