apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
