apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  nodePathMap: |
    [
      {
        "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
        "paths": ["/mnt/nvme/k8s-storage"]
      }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvme-local-path-config
  namespace: kube-system
data:
  config.json: |
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/mnt/nvme/k8s-storage"]
        }
      ]
    }
  helperPod.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: "rancher/mirrored-library-busybox:1.36.1"
        imagePullPolicy: IfNotPresent
  setup: |
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "${VOL_DIR}"
    chmod 700 "${VOL_DIR}/.."
  teardown: |
    #!/bin/sh
    set -eu
    rm -rf "${VOL_DIR}"
