apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: helm/prometheus-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
