apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
  ipAllowList:
    sourceRange:
      - 10.0.0.1/24
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: argocd-allowlist@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argocd.home.local
      secretName: argocd-tls
  rules:
    - host: argocd.home.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
