apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.7.0
    helm:
      releaseName: prometheus
      values: |-
        grafana:
          # TODO: Change this once secret manager/Vault is implemented
          adminPassword: "admin"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
