apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: helm/n8n
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application-eng
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
