{{- if .Values.sealedSecret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "n8n.fullname" . }}-lb-ip
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  encryptedData:
    loadBalancerIP: {{ .Values.sealedSecret.encryptedData.loadBalancerIP }}
  template:
    metadata:
      name: {{ include "n8n.fullname" . }}-lb-ip
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
{{- end }}
