# Default values for Atlantis Helm chart

# Atlantis image configuration
image:
  repository: runatlantis/atlantis
  tag: latest
  pullPolicy: IfNotPresent

# Atlantis server configuration
server:
  port: 4141

# GitHub configuration
github:
  user: ""
  token: ""
  repoWhitelist: "https://github.com/nwthomas/gitops"

# Kubernetes service configuration
service:
  type: ClusterIP
  port: 80

# Resources
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Ingress configuration (optional)
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: atlantis.example.com
      paths:
        - /
  tls: []
