apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: eng
            server: https://kubernetes.default.svc
          - environment: prd
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{environment}}-apps"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/nwthomas/gitops.git
        targetRevision: main
        path: argocd/apps/{{environment}}
        directory:
          recurse: true
      destination:
        server: "{{server}}"
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
