apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-eng-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.12.3
    helm:
      values: |
        installCRDs: true
        prometheus:
          enabled: true
        serviceAccount:
          create: true
          name: cert-manager-eng-app
        rbac:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-eng
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
