{{- if .Values.internalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  ports:
    - name: web
      port: {{ .Values.internalService.port }}
      targetPort: web
  selector:
    prometheus: prometheus-persistant
  sessionAffinity: {{ .Values.internalService.sessionAffinity }}
{{- end }}
