apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: helm/atlantis
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
