# Default values for kube-state-metrics
replicaCount: 1

image:
  repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  tag: "v2.9.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
