apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: main
    path: argocd/apps/secrets-system/secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
