apiVersion: v2
name: argocd
description: ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes
type: application
version: 2.8.4
appVersion: "2.8.4"
keywords:
  - argocd
  - gitops
  - kubernetes
home: https://argoproj.github.io/argo-cd/
sources:
  - https://github.com/argoproj/argo-cd
maintainers:
  - name: ArgoCD Team
    email: argocd@argoproj.io
dependencies:
  - name: argo-cd
    version: 5.51.6
    repository: https://argoproj.github.io/argo-helm
