# ArgoCD Helm Chart Values
# This chart deploys ArgoCD using the official argo-cd Helm chart

argo-cd:
  # Global settings
  global:
    imageRegistry: ""
    imagePullSecrets: []

  # ArgoCD server configuration
  server:
    service:
      type: ClusterIP
    # TODO: Move to a secret for IP and LB type service
    # Uncomment and configure when ready for external access
    # ingress:
    #   enabled: true
    #   ingressClassName: traefik
    #   hosts:
    #     - argocd.yourdomain.com
    #   tls:
    #     - secretName: argocd-tls
    #       hosts:
    #         - argocd.yourdomain.com
    # Security improvements
    extraArgs:
      - --insecure
    adminPassword: ""  # Set via sealed secret
    adminPasswordMtime: ""

  # Application controller configuration
  controller:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  # ApplicationSet controller
  applicationSet:
    enabled: true

  # RBAC configuration
  rbac:
    create: true

  # Namespace
  namespace:
    create: true
    name: argocd

  # High availability (optional - uncomment if you want HA)
  # controller:
  #   replicas: 2
  # repoServer:
  #   replicas: 2
  # server:
  #   replicas: 2

  # Redis configuration (if needed)
  redis:
    enabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"

  # Dex configuration (if needed for SSO)
  dex:
    enabled: false
    # Configure when ready for SSO
    # config:
    #   connectors:
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientID: your-github-client-id
    #         clientSecret: your-github-client-secret
