argo-cd:
  server:
    service:
      type: ClusterIP
  controller:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  configs:
     existingSecret: "this is a test"
  applicationSet:
    enabled: true
  rbac:
    create: false