apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nwthomas/gitops.git
    targetRevision: HEAD
    path: helm/cert-manager
    helm:
      values: |
        # Override default values if needed
        email: "cert.manager.k7f9z@gmail.com"
        ingressClassName: "traefik"

        letsencryptStaging:
          enabled: true
          email: "cert.manager.k7f9z@gmail.com"
          
        letsencryptProduction:
          enabled: true
          email: "cert.manager.k7f9z@gmail.com"
          
        selfsigned:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - SkipDryRunOnMissingResource=true
