apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlantis.fullname" . }}-secrets
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
type: Opaque
data:
  # GitHub token (base64 encoded)
  # You need to create this secret manually with your GitHub token
  github-token: ""  # base64 encoded GitHub token
  {{- if .Values.atlantis.env.GITHUB_APP_ID }}
  # GitHub App private key (base64 encoded)
  # You need to create this secret manually with your GitHub App private key
  github-app-key: ""  # base64 encoded GitHub App private key
  {{- end }}
