apiVersion: v2
name: longhorn
description: A Helm chart for Longhorn distributed block storage
type: application
version: 0.1.0
appVersion: "1.9.1"
dependencies:
  - name: longhorn
    version: 1.9.1
    repository: https://charts.longhorn.io
