name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Helm lint all charts
        run: |
          for dir in $(find helm -maxdepth 2 -type f -name Chart.yaml | xargs -n1 dirname); do
            echo "Linting ${dir}"
            helm lint $dir
          done
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - name: Terraform init & validate
        working-directory: terraform
        run: |
          terraform init -backend=false -input=false
          terraform validate
